=== SudipKumarMahato/Digital-Nepal-XML-Website/catalog_20049066.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="digitalnepal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="storeHeading">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="headingMaxWidth">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="headingLogo" />
                                        <xs:element name="headingLinkContainer">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="headingLink" maxOccurs="unbounded" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute type="xs:string" name="status" use="optional" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="headingInfo">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="userProfile">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="userImageConatiner">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element type="xs:string" name="userImage" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="userDropContentContainer">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="userDropContent">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="dropItem" maxOccurs="unbounded" minOccurs="0">
                                                                                            <xs:complexType mixed="true">
                                                                                                <xs:sequence>
                                                                                                    <xs:element name="dropIcon">
                                                                                                        <xs:complexType>
                                                                                                            <xs:simpleContent>
                                                                                                                <xs:extension base="xs:string">
                                                                                                                    <xs:attribute type="xs:string" name="content" use="optional" />
                                                                                                                </xs:extension>
                                                                                                            </xs:simpleContent>
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="storeContent">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="storeDescription">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="descriptionLeft">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="descriptionLogo" />
                                                    <xs:element type="xs:string" name="descriptionHeading" />
                                                    <xs:element type="xs:string" name="descriptionPara" />
                                                    <xs:element type="xs:string" name="descriptionButton" />
                                                    <xs:element name="contacts">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="address">
                                                                    <xs:complexType mixed="true">
                                                                        <xs:sequence>
                                                                            <xs:element type="xs:string" name="addressIcon" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="telephone">
                                                                    <xs:complexType mixed="true">
                                                                        <xs:sequence>
                                                                            <xs:element type="xs:string" name="telephoneIcon" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="mail">
                                                                    <xs:complexType mixed="true">
                                                                        <xs:sequence>
                                                                            <xs:element type="xs:string" name="mailIcon" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="descriptionRight">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="sliderContainer">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="slider">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element type="xs:string" name="sliderImage" />
                                                                            <xs:element type="xs:string" name="sliderInfo" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="storeProducts">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="product" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="productView">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="productImageContainer">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element type="xs:string" name="productImage" />
                                                                            <xs:element name="productHover">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="productPreview">
                                                                                            <xs:complexType mixed="true">
                                                                                                <xs:sequence>
                                                                                                    <xs:element type="xs:string" name="previewIcon" />
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                        <xs:element name="productWishlist">
                                                                                            <xs:complexType mixed="true">
                                                                                                <xs:sequence>
                                                                                                    <xs:element type="xs:string" name="wishlistIcon" />
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="productButtonContainer">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element type="xs:string" name="buyButton" />
                                                                            <xs:element type="xs:string" name="addCartButton" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="productDetail">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="detailContainer" maxOccurs="unbounded" minOccurs="0">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element type="xs:string" name="detailQuestion" />
                                                                            <xs:element type="xs:string" name="detailAnswer" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute type="xs:string" name="product" use="optional" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SudipKumarMahato/Digital-Nepal-XML-Website/catalog_20049066.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- linking the external css in the file -->
<?xml-stylesheet href="./catalog_20049066.css" type="text/css"?>
<!--creating root element digitalnepal containing all the elements -->
<digitalnepal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_20049066.xsd">
    <!--heading element starts here -->
    <storeHeading>

        <headingMaxWidth>
            <!--logo of the webpage -->
            <headingLogo />

            <!--navigation links -->
            <headingLinkContainer>
                <headingLink status="active">Home</headingLink>
                <headingLink status="inactive">Products</headingLink>
                <headingLink status="inactive">Services</headingLink>
                <headingLink status="inactive">Contact us</headingLink>
                <headingLink status="inactive">Cards</headingLink>
            </headingLinkContainer>


            <!-- making the shortcut navigation -->
            <headingInfo>
                <!-- making the userProfile -->
                <userProfile>
                    <userImageConatiner>
                        <userImage />
                    </userImageConatiner>
                    <userDropContentContainer>
                        <userDropContent>
                            <dropItem>
                                <dropIcon content="user" />
                                My Profile
                            </dropItem>
                            <dropItem>
                                <dropIcon content="wishlist" />
                                My Wishlist
                            </dropItem>
                            <dropItem>
                                <dropIcon content="order" />
                                My Order
                            </dropItem>
                            <dropItem>
                                <dropIcon content="delivery" />
                                Delivery
                            </dropItem>
                            <dropItem>
                                <dropIcon content="help" />
                                Help
                            </dropItem>
                            <dropItem>
                                <dropIcon content="logout" />
                                Logout
                            </dropItem>
                        </userDropContent>
                    </userDropContentContainer>
                </userProfile>
            </headingInfo>
        </headingMaxWidth>
    </storeHeading>

    <!--the store products and description starts here -->
    <storeContent>
        <storeDescription>
            <descriptionLeft>
                <descriptionLogo />
                <descriptionHeading>DIGITAL NEPAL</descriptionHeading>
                <descriptionPara>Digital Nepal is the leading giftcard website, and it is our mission to provide smiles by offering personalized git cards and customers greetings. It is the best place to buy e-gift card, Visa, choice cards or bulk gift cards online.</descriptionPara>
                <descriptionButton>Learn More</descriptionButton>
                <contacts>
                    <address>
                        <addressIcon />
                        London, United Kingdom
                    </address>
                    <telephone>
                        <telephoneIcon />
                        +933 9816725300
                    </telephone>
                    <mail>
                        <mailIcon />
                        digitalnepal@gmail.com
                    </mail>
                </contacts>

            </descriptionLeft>
            <descriptionRight>
                <sliderContainer>
                    <slider>
                        <sliderImage />
                        <sliderInfo></sliderInfo>
                    </slider>

                </sliderContainer>
            </descriptionRight>
        </storeDescription>
        <!--the store products and description starts here -->


        <!-- making the store products -->
        <storeProducts>
            <!-- making the store product No.1 -->
            <product product="product1">
                <productView>
                    <!-- making the store product hover -->
                    <productImageContainer>
                        <productImage />
                        <productHover>
                            <productPreview>
                                <previewIcon />
                                Preview
                            </productPreview>
                            <productWishlist>
                                <wishlistIcon />
                                Wishlist
                            </productWishlist>
                        </productHover>
                    </productImageContainer>
                    <productButtonContainer>
                        <buyButton>Purchase</buyButton>
                        <addCartButton>Add to Cart</addCartButton>
                    </productButtonContainer>
                </productView>
                <productDetail>
                    <detailContainer>
                        <detailQuestion>Name : </detailQuestion>
                        <detailAnswer>Google Play Store</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Brand : </detailQuestion>
                        <detailAnswer>Google</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Availability: </detailQuestion>
                        <detailAnswer>Yes</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Type : </detailQuestion>
                        <detailAnswer>Digital</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Validity : </detailQuestion>
                        <detailAnswer>2 Months</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Maximum User : </detailQuestion>
                        <detailAnswer>5</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Delivery : </detailQuestion>
                        <detailAnswer>G-Mail</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Price : </detailQuestion>
                        <detailAnswer>$ 50</detailAnswer>
                    </detailContainer>
                </productDetail>
            </product>

            <!-- making the store product No.2 -->
            <product product="product2">
                <productView>
                    <!-- making the store product hover -->
                    <productImageContainer>
                        <productImage />
                        <productHover>
                            <productPreview>
                                <previewIcon />
                                Preview
                            </productPreview>
                            <productWishlist>
                                <wishlistIcon />
                                Wishlist
                            </productWishlist>
                        </productHover>
                    </productImageContainer>
                    <productButtonContainer>
                        <buyButton>Purchase</buyButton>
                        <addCartButton>Add to Cart</addCartButton>
                    </productButtonContainer>
                </productView>
                <productDetail>
                    <detailContainer>
                        <detailQuestion>Name : </detailQuestion>
                        <detailAnswer>PUBG Mobile UC Card</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Brand : </detailQuestion>
                        <detailAnswer>PUBG</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Availability: </detailQuestion>
                        <detailAnswer>No</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Type : </detailQuestion>
                        <detailAnswer>Digital</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Discount : </detailQuestion>
                        <detailAnswer>25%</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Maximum User : </detailQuestion>
                        <detailAnswer>5</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Delivery : </detailQuestion>
                        <detailAnswer>G-Mail</detailAnswer>
                    </detailContainer>
                    <detailContainer>
                        <detailQuestion>Price : </detailQuestion>
                        <detailAnswer>$ 150</detailAnswer>
                    </detailContainer>
                </productDetail>
            </product>
            <!-- making the store product No.3 -->
            <product product="product3">
                <productView>
                    <!-- making the store product hover -->
                    <productImageContainer>
                        <productImage />
                        <productHover>
                            <productPreview>
